version: '3.8'

networks:
  stealthycoder_local:

volumes:
  gradle_cache:

services:
  app:
    build:
      context: ./provision/docker/backend/local
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5005:5005"
      - "127.0.0.1:5006:5006"
    user: ${DOCKER_UID:-1001}
    volumes:
      - gradle_cache:/data/gradle
      - ./code:/srv/http
    environment:
      SUSPEND_DEBUG: 'n'
    networks:
      - stealthycoder_local
  